name: CI
on :
 - push
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/cicd-lectures/gitpod:latest
      options: --user=root
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: mvn package
      - run: git add target/menu-server.jar
      - run: git config --global user.name JulesPierrat
      - run: git commit -m "Jar upload"
      - run: git push origin main      